export const avatarDressConstants = {
    AVATAR_DRESS_REQUEST: 'AVATAR_DRESS_REQUEST',
    AVATAR_DRESS_SUCCESS: 'AVATAR_DRESS_SUCCESS',
    AVATAR_DRESS_FAILURE: 'AVATAR_DRESS_FAILURE',
    
    AVATAR_GETALL_REQUEST: 'AVATAR_GETALL_REQUEST',
    AVATAR_GETALL_SUCCESS: 'AVATAR_GETALL_SUCCESS',
    AVATAR_CREATE_SUCCESS: 'AVATAR_CREATE_SUCCESS',

    AVATAR_GET_REQUEST: 'AVATAR_GET_REQUEST',
    AVATAR_GET_SUCCESS: 'AVATAR_GET_SUCCESS',
};
