export const avatarDressConstants = {
    AVATAR_DRESS_REQUEST: 'AVATAR_DRESS_REQUEST',
    AVATAR_DRESS_SUCCESS: 'AVATAR_DRESS_SUCCESS',
    AVATAR_DRESS_FAILURE: 'AVATAR_DRESS_FAILURE',
    // LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    // LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    // LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    // LOGOUT: 'USERS_LOGOUT',

    AVATAR_GETALL_REQUEST: 'AVATAR_GETALL_REQUEST',
    AVATAR_GETALL_SUCCESS: 'AVATAR_GETALL_SUCCESS',
    AVATAR_CREATE_SUCCESS: 'AVATAR_CREATE_SUCCESS',

    AVATAR_GET_REQUEST: 'AVATAR_GET_REQUEST',
    AVATAR_GET_SUCCESS: 'AVATAR_GET_SUCCESS',
    // GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    // DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    // DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    // DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
};
